version: '3'

services:
  web:
    build: .
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/store_drf
    ports:
      - 8000:8000
    env_file:
      - ./core/.env
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_DB=XXXXX
      - POSTGRES_USER=XXXXX
      - POSTGRES_PASSWORD=XXXXX
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data: